// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTui0URlzkNq3hnbQg8Tuos3BRfxojD0',
    appId: '1:623419457400:android:aa7276c2b6c7257ab0928d',
    messagingSenderId: '623419457400',
    projectId: 'chacha-caller',
    storageBucket: 'chacha-caller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaCQKwTdTg_TXGl4ymAx9_0gUJQ3XJlzs',
    appId: '1:623419457400:ios:cc097b28fe29f918b0928d',
    messagingSenderId: '623419457400',
    projectId: 'chacha-caller',
    storageBucket: 'chacha-caller.appspot.com',
    iosBundleId: 'com.example.chachaCaller',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Dc3tw-MV_8vWA1rktJ6xCwp-GRUAOJ4',
    appId: '1:623419457400:web:c6e670dcf3d061cab0928d',
    messagingSenderId: '623419457400',
    projectId: 'chacha-caller',
    authDomain: 'chacha-caller.firebaseapp.com',
    storageBucket: 'chacha-caller.appspot.com',
    measurementId: 'G-2MMY0NSC82',
  );

}